<a href="https://colab.research.google.com/github/IgorOlszewski2000/data-science/blob/main/10matrixmultiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([[5,3 ],[3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)


[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [ ]:
Z.shape

(2, 1)

In [ ]:
X = np.array([[2, -1 ,3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
             [0, -1, 2],
             [3, 2, 0]])
print(X, '\n')
print(Y)

np.dot(X,Y)

# macierz tyle ile będzie wierszy w pierwszej macierzy i kolumn w drugiej macierzy ( taki będzie miała wymiar)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


array([[13,  9, -4],
       [ 6,  2, -1]])