<a href="https://colab.research.google.com/github/IgorOlszewski2000/data-science/blob/main/11solving.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [5]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [7]:
A_inv = np.linalg.inv(A)
X=np.dot(A_inv, B)
X

array([[1.],
       [2.]])