<a href="https://colab.research.google.com/github/IgorOlszewski2000/data-science/blob/main/12matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Wyznacznik macierzy

In [3]:
A = np.array([[2,4], [-1,3]])
round(np.linalg.det(A))

10

Ślad macierzy

In [ ]:
# suma elementów po przekątnej

In [4]:
A = np.array([[2,4], [-1,3]])

np.trace(A)

5

Macierz jednostkowa

In [5]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna

In [8]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [10]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A,B)
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana (zamiana wierszy na kolumny itd.)

In [12]:
A
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [14]:
A

array([[ 2,  4],
       [-1,  3]])

In [13]:
A.T

array([[ 2, -1],
       [ 4,  3]])