<a href="https://colab.research.google.com/github/IgorOlszewski2000/data-science/blob/main/13statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
price = np. array([[12.40, 12.80, 11.90, 12.60, 1000],
                   [12.50, 13.00, 11.70, 12.20, 2000],
                   [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [3]:
price.sum()

4650.1

In [4]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [5]:
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [6]:
np.sum(price)

4650.1

In [8]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [9]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

In [10]:
np.median(price)

12.6

In [11]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

Ochylenie standardowe

In [12]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

Wariancja

In [13]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])