<a href="https://colab.research.google.com/github/IgorOlszewski2000/data-science/blob/main/1numpyintro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [8]:
print(x)
type(x)

[1 3]


numpy.ndarray

In [21]:
x.ndim # wymiar naszej tablicy

2

In [12]:
x.shape #kształt
x.size #rozmiar
x.dtype #typ danych

dtype('int64')

In [15]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [16]:
x.dtype

dtype('float64')

In [19]:
x = np.array([[1, 2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [20]:
x.ndim

2

In [22]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [23]:
x.shape

(2, 3)

In [25]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [27]:
x.ndim

3