<a href="https://colab.research.google.com/github/IgorOlszewski2000/data-science/blob/main/4operationsonarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [3]:
A + B

array([6, 0, 7, 4])

In [4]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [5]:
A + 3

array([6, 4, 7, 5])

In [6]:
2 * A

array([6, 2, 8, 4])

In [7]:
np.add(A, B)

array([6, 0, 7, 4])

In [8]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [9]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [10]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [12]:
X = np.array([[1,3] , [-2,0]])
Y = np.array([[6,0] , [-1,2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [16]:
np.dot(X,Y) # mnozenie maciezowe

array([[  3,   6],
       [-12,   0]])

In [17]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [18]:
X @ Y # tez mnozenie maciezowe

array([[  3,   6],
       [-12,   0]])