<a href="https://colab.research.google.com/github/IgorOlszewski2000/data-science/blob/main/7indexcuttarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
# A[idx], A[start:stop], A [:stop], A[start:]

In [4]:
A[2]

2

In [5]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [6]:
A[:2]

array([0, 1])

In [7]:
A[[0, 2]]

array([0, 2])

In [8]:
A[-1]

19

In [9]:
A[2:17]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [10]:
A.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
A[0]

array([0, 1, 2, 3, 4])

In [16]:
A[:, 0]

array([ 0,  5, 10, 15])

In [17]:
A[:, -1]

array([ 4,  9, 14, 19])

In [18]:
A[1,1]

6

In [19]:
A[1:2,1:4]

array([[6, 7, 8]])

In [22]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])